"use client";

import { useCallback, useEffect, useState } from "react";
import { createClient } from "../lib/supabase/client";

type Draft = { id: string; sku?: string; offerId?: string; title?: string; price?: string; quantity?: number; status?: string; imageUrls?: string[] };
type Listing = { listingId?: string; title?: string; price?: string; quantity?: number; status?: string; imageUrls?: string[]; source?: string };
type Margin = { sourcePrice: number; sellingPrice: number; recommendedSalePrice: number; ebayFee: number; profit: number; marginPercent: number };
type Automation = { inventory: { total: number; active: number; lowStock: number; outOfStock: number; attention: Array<{ id: string; title: string; asin: string; stock: number }> }; margin: Margin; tracking: { configured: boolean; total: number; withTracking: number; awaitingTracking: number; shipments: Array<{ orderId: string; status: string; trackingNumber?: string | null }> } };
const money = new Intl.NumberFormat("de-DE", { style: "currency", currency: "EUR" });

export function EbayDashboard({ email }: { email: string }) {
  const [drafts, setDrafts] = useState<Draft[]>([]); const [listings, setListings] = useState<Listing[]>([]); const [automation, setAutomation] = useState<Automation | null>(null); const [listedCount, setListedCount] = useState<number | null>(null); const [margin, setMargin] = useState<Margin | null>(null); const [sourcePrice, setSourcePrice] = useState("20"); const [targetMargin, setTargetMargin] = useState("20"); const [mappingItemId, setMappingItemId] = useState(""); const [mappingAmazonUrl, setMappingAmazonUrl] = useState(""); const [mappingNotice, setMappingNotice] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(true); const [supabase] = useState(createClient);
  const api = useCallback(async (path: string, init: RequestInit = {}) => { const { data: { session } } = await supabase.auth.getSession(); const response = await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL || ""}/api/v1${path}`, { ...init, headers: { "Content-Type": "application/json", ...(session?.access_token ? { Authorization: `Bearer ${session.access_token}` } : {}), ...(init.headers || {}) }, cache: "no-store" }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Dashboard konnte nicht geladen werden."); return body; }, [supabase]);
  const refresh = useCallback(async () => { setBusy(true); setError(""); try { const [draftBody, automationBody, listingsBody] = await Promise.all([api("/ebay/drafts"), api("/automation/overview"), api("/ebay/active-listings")]); setDrafts(draftBody.drafts || []); setListings(listingsBody.listings || []); setAutomation(automationBody); setMargin(automationBody.margin || null); setListedCount(listingsBody.configured ? (listingsBody.listings || []).length : automationBody.inventory?.active ?? null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Dashboard konnte nicht geladen werden."); } finally { setBusy(false); } }, [api]);
  useEffect(() => { void refresh(); }, [refresh]);
  async function calculateMargin() { try { const result = await api("/automation/margin/calculate", { method: "POST", body: JSON.stringify({ sourcePrice, targetMarginPercent: targetMargin }) }); setMargin(result); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Berechnung fehlgeschlagen."); } }
  async function saveMapping() { try { await api("/automation/mapping", { method: "POST", body: JSON.stringify({ itemId: mappingItemId, amazonUrl: mappingAmazonUrl }) }); setMappingItemId(""); setMappingAmazonUrl(""); setMappingNotice("Amazon-Zuordnung gespeichert."); } catch (cause) { setMappingNotice(cause instanceof Error ? cause.message : "Zuordnung konnte nicht gespeichert werden."); } }
  async function publishDraft(draft: Draft) { if (!draft.offerId || !draft.sku) { setError("Für dieses Produkt fehlen eBay-Angebots-ID oder SKU."); return; } try { setError(""); await api("/ebay/publish", { method: "POST", body: JSON.stringify({ offerId: draft.offerId, sku: draft.sku }) }); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Das Produkt konnte nicht veröffentlicht werden."); } }
  async function logout() { await supabase.auth.signOut(); window.location.assign("/login"); }
  const inventory = automation?.inventory; const tracking = automation?.tracking;
  return <main className="webDashboard">
    <header className="dashboardHeader"><div><span className="sectionEyebrow">AUTOLISTER · EBAY.DE</span><h1>Admin Operations Dashboard</h1></div><div className="dashboardUser"><span>{email} · Administrator</span><button className="quietButton" onClick={logout}>Ausloggen</button></div></header>
    <section className="dashboardStats"><article><span>Wartende Produkte</span><strong>{drafts.length}</strong></article><article><span>Gelistet auf eBay</span><strong>{listedCount ?? "—"}</strong></article><article><span>Sync-Warnungen</span><strong>{inventory ? inventory.lowStock + inventory.outOfStock : "—"}</strong></article></section>
    {error ? <p className="authError">{error}</p> : null}
    <nav className="dashboardTabs" aria-label="Dashboard Bereiche"><a href="#live">Auf eBay Aktiv</a><a href="#pool">Produktpool</a><a href="#automation">Synchronisation</a><a href="#matcher">Amazon Matcher</a><a href="#archive">Archiv</a><a href="#settings">Einstellungen</a></nav>
    <section id="automation" className="automationGrid">
      <article className="dashboardCard"><div className="dashboardCardHeading"><div><p className="sectionEyebrow">Stok & Preis</p><h2>Synchronisationsmotor</h2></div><button className="quietButton" onClick={() => void refresh()}>Aktualisieren</button></div><div className="moduleMetrics"><span><b>{inventory?.total ?? "—"}</b> Produkte überwacht</span><span><b>{inventory?.lowStock ?? "—"}</b> Niedriger Bestand</span><span><b>{inventory?.outOfStock ?? "—"}</b> Nicht verfügbar</span></div>{inventory?.attention?.length ? <ul className="attentionList">{inventory.attention.map((item) => <li key={item.id}><span>{item.title}</span><b>{item.stock} Stk.</b></li>)}</ul> : <p className="emptyDashboard">Keine Bestandswarnungen.</p>}</article>
      <article className="dashboardCard"><div><p className="sectionEyebrow">Pricing</p><h2>Gewinn & Provision</h2></div><div className="marginInputs"><label>Amazon-Preis<input inputMode="decimal" value={sourcePrice} onChange={(event) => setSourcePrice(event.target.value)} /></label><label>Zielmarge %<input inputMode="decimal" value={targetMargin} onChange={(event) => setTargetMargin(event.target.value)} /></label><button className="primaryButton" onClick={() => void calculateMargin()}>Berechnen</button></div>{margin ? <div className="marginResult"><span>Empfohlener eBay-Preis<strong>{money.format(margin.recommendedSalePrice)}</strong></span><span>Gewinn<strong>{money.format(margin.profit)} · {margin.marginPercent}%</strong></span></div> : <p className="emptyDashboard">Berechnung wird geladen …</p>}</article>
      <article className="dashboardCard"><div className="dashboardCardHeading"><div><p className="sectionEyebrow">Fulfillment</p><h2>Tracking-Nummern</h2></div><span className={tracking?.configured ? "statusChip" : "statusChip mutedChip"}>{tracking?.configured ? "Verbunden" : "eBay verbinden"}</span></div><div className="moduleMetrics"><span><b>{tracking?.total ?? "—"}</b> Bestellungen</span><span><b>{tracking?.withTracking ?? "—"}</b> Mit Tracking</span><span><b>{tracking?.awaitingTracking ?? "—"}</b> Offen</span></div>{tracking?.shipments?.length ? <ul className="attentionList">{tracking.shipments.slice(0, 3).map((shipment) => <li key={shipment.orderId}><span>{shipment.orderId}</span><b>{shipment.trackingNumber || "Tracking fehlt"}</b></li>)}</ul> : <p className="emptyDashboard">Noch keine eBay-Sendungen verfügbar.</p>}</article>
    </section>
    <section id="live" className="dashboardCard"><div className="dashboardCardHeading"><div><p className="sectionEyebrow">eBay Live</p><h2>Auf eBay Aktiv</h2></div><span className="statusChip">{listings.length} Listings</span></div>{busy ? <p>Live-Angebote werden geladen …</p> : listings.length === 0 ? <p className="emptyDashboard">Keine veröffentlichten eBay-Angebote gefunden.</p> : <div className="productGrid">{listings.map((listing) => <article className="productCard" key={listing.listingId}>{listing.imageUrls?.[0] ? <img src={listing.imageUrls[0]} alt="" loading="lazy" /> : <div className="productPlaceholder" />}<div><strong>{listing.title || "Ohne Titel"}</strong><small>Item ID: {listing.listingId || "—"} · {listing.price || "—"} · {listing.quantity ?? 0} Stück</small></div><span className="statusChip">Aktiv</span></article>)}</div>}</section>
    <section id="pool" className="dashboardCard"><div className="dashboardCardHeading"><div><p className="sectionEyebrow">Produktpool</p><h2>Bereite &amp; Live</h2></div><button className="quietButton" onClick={() => void refresh()}>Aktualisieren</button></div>{busy ? <p>Produktdaten werden geladen …</p> : drafts.length === 0 ? <p className="emptyDashboard">Keine Drafts vorhanden.</p> : <div className="productGrid">{drafts.map((draft) => <article className="productCard" key={draft.id}>{draft.imageUrls?.[0] ? <img src={draft.imageUrls[0]} alt="" /> : <div className="productPlaceholder" />}<div><strong>{draft.title || "Ohne Titel"}</strong><small>{draft.price || "—"} · {draft.quantity ?? 0} Stück</small></div><span className="statusChip">{draft.status || "READY"}</span>{draft.offerId ? <button className="primaryButton" onClick={() => void publishDraft(draft)}>Auf eBay veröffentlichen</button> : null}</article>)}</div>}</section>
    <section id="matcher" className="dashboardCard"><div><p className="sectionEyebrow">Legacy Inventory Matcher</p><h2>Amazon-Produkt manuell verknüpfen</h2></div><div className="mappingInputs"><label>eBay Item ID<input value={mappingItemId} onChange={(event) => setMappingItemId(event.target.value)} placeholder="z. B. 407164679608" /></label><label>Amazon ASIN oder URL<input value={mappingAmazonUrl} onChange={(event) => setMappingAmazonUrl(event.target.value)} placeholder="https://www.amazon.de/dp/B0..." /></label><button className="primaryButton" onClick={() => void saveMapping()}>Zuordnung speichern</button></div>{mappingNotice ? <p className="authNotice">{mappingNotice}</p> : null}</section>
    <section id="archive" className="dashboardCard"><div><p className="sectionEyebrow">Archiv</p><h2>Gelöschte und zurückgesetzte Entwürfe</h2></div><p className="emptyDashboard">Das Archiv wird aus dem eBay-Bridge-Verlauf synchronisiert.</p></section>
    <section id="settings" className="dashboardCard"><div><p className="sectionEyebrow">Einstellungen</p><h2>eBay Verbindung</h2></div><p className="emptyDashboard">Die eBay OAuth- und Policy-Einstellungen bleiben geschützt im Backend.</p></section>
  </main>;
}
