VEHICLE_REFERENCES = [
    {
        "brand": "VW",
        "model": "Golf",
        "keywords": ["golf"],
        "baseline_year": 2007,
        "baseline_km": 155000,
        "market_price": 3150,
        "sell_days": "10-18 gun",
    },
    {
        "brand": "Opel",
        "model": "Corsa",
        "keywords": ["corsa"],
        "baseline_year": 2008,
        "baseline_km": 140000,
        "market_price": 2550,
        "sell_days": "8-16 gun",
    },
    {
        "brand": "Ford",
        "model": "Focus",
        "keywords": ["focus"],
        "baseline_year": 2007,
        "baseline_km": 165000,
        "market_price": 2800,
        "sell_days": "11-20 gun",
    },
    {
        "brand": "Skoda",
        "model": "Fabia",
        "keywords": ["fabia"],
        "baseline_year": 2009,
        "baseline_km": 130000,
        "market_price": 2950,
        "sell_days": "9-15 gun",
    },
    {
        "brand": "Skoda",
        "model": "Octavia",
        "keywords": ["octavia", "1.9 tdi"],
        "baseline_year": 2006,
        "baseline_km": 155000,
        "market_price": 3000,
        "sell_days": "9-17 gun",
        "liquidity_note": "Octavia 1.9 TDI temiz orneklerde hala likit bir cikis aracidir.",
    },
    {
        "brand": "Seat",
        "model": "Ibiza",
        "keywords": ["ibiza"],
        "baseline_year": 2008,
        "baseline_km": 140000,
        "market_price": 2700,
        "sell_days": "9-16 gun",
    },
    {
        "brand": "Toyota",
        "model": "Yaris",
        "keywords": ["yaris"],
        "baseline_year": 2007,
        "baseline_km": 135000,
        "market_price": 3200,
        "sell_days": "8-14 gun",
    },
]

ISSUE_LIBRARY = [
    {
        "keywords": [
            "ohne tuv",
            "ohne tuev",
            "tuv abgelaufen",
            "tuev abgelaufen",
            "hu fallig",
            "hu faellig",
            "tuv yazin bitiyor",
            "muayene",
        ],
        "label": "TUV / muayene",
        "repair_range": (80, 250),
        "risk_score": 16,
    },
    {"keywords": ["motorleuchte", "motor lambasi", "check engine"], "label": "Motor ikaz", "repair_range": (180, 650), "risk_score": 24},
    {
        "keywords": ["klima sogutmuyor", "klima bozuk", "klima ariza", "ac not cold"],
        "label": "Klima",
        "repair_range": (120, 380),
        "risk_score": 10,
    },
    {
        "keywords": ["kupplung rutscht", "kupplung defekt", "debriyaj kaciriyor", "debriyaj"],
        "label": "Kupplung",
        "repair_range": (350, 900),
        "risk_score": 24,
    },
    {"keywords": ["springt nicht", "calismiyor"], "label": "Calismama", "repair_range": (180, 700), "risk_score": 28},
    {"keywords": ["aku", "batterie"], "label": "Aku", "repair_range": (60, 150), "risk_score": 8},
    {"keywords": ["rost", "pas"], "label": "Rost / pas", "repair_range": (250, 900), "risk_score": 22},
    {"keywords": ["unfall", "hasar"], "label": "Hasar", "repair_range": (350, 1400), "risk_score": 30},
    {"keywords": ["fren", "bremse"], "label": "Fren", "repair_range": (120, 320), "risk_score": 12},
    {"keywords": ["lastik", "reifen"], "label": "Lastik", "repair_range": (180, 420), "risk_score": 10},
    {
        "keywords": ["oel", "ol leak", "oil leak", "verliert ol", "verlieren ol", "verlieren aber ol", "olverlust"],
        "label": "Yag kacagi",
        "repair_range": (180, 620),
        "operator_range": (80, 240),
        "risk_score": 18,
    },
    {
        "keywords": ["querlenker", "control arm", "alt salincak", "salincak", "gerosche", "gerausche"],
        "label": "Querlenker / on takim sesi",
        "repair_range": (180, 420),
        "operator_range": (90, 220),
        "risk_score": 14,
    },
    {
        "keywords": ["wartung", "bakim", "serviceheft", "service"],
        "label": "Temel bakim",
        "repair_range": (90, 240),
        "operator_range": (55, 140),
        "risk_score": 8,
    },
]

POSITIVE_SIGNAL_LIBRARY = [
    {"keywords": ["fahrbereit"], "label": "Arac yurutur durumda beyan edildi", "risk_reduction": 4},
    {"keywords": ["einwandfrei"], "label": "Motor / sanziman / kupplung iyi beyan edildi", "risk_reduction": 5},
    {"keywords": ["tuv bis", "tuev bis"], "label": "Gecerli TUV bilgisi var", "risk_reduction": 4},
]

HAMBURG_CITY_ALIASES = [
    "hamburg",
    "wandsbek",
    "altona",
    "harburg",
    "bergedorf",
    "eimsbuettel",
    "eimsbuttel",
    "winterhude",
    "barmbek",
    "stellingen",
    "pinneberg",
    "norderstedt",
]

HAMBURG_BUY_BOX = {
    "preferred_city": "Hamburg",
    "max_asking_price": 5000,
    "min_net_profit": 550,
    "min_margin_percent": 18,
    "max_km_benzin": 210000,
    "max_km_diesel": 190000,
    "min_year": 2005,
    "max_risk_level": "medium",
}
