const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const manifest = JSON.parse(read("manifest.json"));
const background = read("background.js");
const content = read("content.js");
const options = read("options.js");
const bridge = read("bridge/server.js");
const listingBuilder = read("listing_builder.js");
const parser = read("amazon_parser.js");
const apiClient = read("bridge/ebay_api_client.js");
const supabaseClient = read("bridge/supabase.js");
const repositories = read("bridge/repositories.js");
const migration = read("supabase/migrations/0001_initial.sql");

assert.ok(manifest.permissions.includes("tabs"));
assert.ok(!manifest.permissions.includes("offscreen"));
assert.ok(!manifest.permissions.includes("declarativeNetRequest"));
assert.ok(!manifest.permissions.includes("alarms"));
assert.ok(manifest.host_permissions.includes("https://*.amazon.de/*"));
assert.ok(!manifest.host_permissions.includes("https://*.amazon.com/*"));
assert.ok(!manifest.host_permissions.includes("https://*.ebay.com/*"));
assert.match(content, /PROCESS_GALLERY_IMAGES/);
assert.match(content, /activeProduct/);
assert.match(background, /targetLongestSide = Math\.max\(500/);
assert.match(background, /REBUILD_DRAFT_FROM_AMAZON/);
assert.match(options, /Kleine Altbilder erkannt/);
assert.match(bridge, /IMAGE_REBUILD_REQUIRED/);
assert.match(bridge, /ebayImageDimensions/);
assert.match(listingBuilder, /Produktbeschreibung/);
assert.match(background, /context\.fillRect\(0, 0, targetWidth, targetHeight\)/);
assert.match(background, /quality: 0\.98/);
assert.match(background, /IMAGE_PIPELINE_VERSION = 8/);
assert.match(background, /Bos\/beyaz gorsel galeriye eklenmedi/);
assert.match(listingBuilder, /REFERENCE_BADGE_LAYOUT_V2/);
assert.match(listingBuilder, /Ana görsel kalite kontrolü başarısız/);
assert.match(parser, /AC_SL1500/);
assert.match(apiClient, /longMessage/);
assert.match(apiClient, /requestId/);
assert.match(bridge, /api\/debug\/events/);
assert.match(background, /SAVE_LEGACY_MAPPING/);
assert.match(background, /ebay\/active-listings\/update/);
assert.match(options, /Legacy-Angebot ist mit Amazon verbunden/);
assert.match(supabaseClient, /auth\.getClaims/);
assert.match(repositories, /legacy_listing_mappings/);
assert.match(migration, /enable row level security/);
assert.match(migration, /tenant_id/);
assert.match(bridge, /supabaseConfigured/);
assert.match(bridge, /CATEGORY_AUTO_CORRECTED/);
assert.match(bridge, /OFFER_CATEGORY_UPDATE/);
assert.doesNotMatch(bridge, /resize\(\{ width: 1400/);
assert.match(content, /usefulSpecifics/);
assert.match(content, /resolveBrand/);

console.log("Release readiness passed: diagnostics, legacy mapping, image guard and publishing flow are wired.");
